### ISSUE TITLE
Creating a CompactSky server and /help doesnt work

### ISSUE THREAD

**Issue by JayPack** [Darkosto/SkyFactory4Issues#276]
```
[18:29:57] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: help
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(Unknown Source) ~[?:1.8.0_191]
        at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.8.0_191]
        at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:1.8.0_191]
        at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0_191]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_191]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_191]
        at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_191]
        at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.command.CommandHelp.func_184900_a(SourceFile:116) ~[cn.class:?]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:71) ~[cn.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```
Works on a Lost Cities server though.

**Comment by deudyscout** [comment]
i am having the same problem, i also cant us the command to create a new island

**Comment by sk2048** [comment]
CompactSky doesn't use Topography; you can't generate new islands. Each player has their own compact machine in the hub world, I believe you can create a server with up to 64 of them.

**Comment by jlu5** [comment]
Same problem here. On v4.0.8 and the default world type, `/help` is completely broken:

```
> help
[06:08:01] [Server thread/INFO] [minecraft/DedicatedServer]: An unknown error occurred while attempting to perform this command
[06:08:01] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: help
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866) ~[?:1.8.0_222]
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483) ~[?:1.8.0_222]
        at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422) ~[?:1.8.0_222]
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:1.8.0_222]
        at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_222]
        at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_222]
        at java.util.ArrayList.sort(ArrayList.java:1462) ~[?:1.8.0_222]
        at java.util.Collections.sort(Collections.java:143) ~[?:1.8.0_222]
        at net.minecraft.command.CommandHelp.func_184900_a(SourceFile:116) ~[cn.class:?]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:71) ~[cn.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
