### ISSUE TITLE
Nether causes the server to lag and crashes a bit later.

### ISSUE THREAD

**Issue by asdfwasfdad** [Darkosto/SkyFactory4Issues#355]
I set up a minecraft server 4.0.1 for sky factory 4.
The server worked perfectly fine until I made the nether cake to go to the nether.
Every time I go to the nether, the server lags really badly and then crashes.
I assumed that the server is just overloaded but when I checked it wasn't even close to reaching 4gb of RAM usage and my internet is perfectly fine.
I reinstalled the files from curse and tried again with another server but the same problem happens.

## Logs
* Crash Log: https://pastebin.com/xpYbmfNf

## World Information
* Preset: Sky Factory 4 Classic (Default world)
* Prestige: Enabled
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.1
* Java Version: Java 8 Update 201 (Not sure what Java Version means)
* Launcher Used: Twitch
* Memory Allocated: 4GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Java 8 Update 201 (Not sure what Java Version means)
* Operating System: Windows 10, 64 bit
* Hoster/Hosting Solution: Hoster
* Sponge (Non-Vanilla Forge) Server: No
* Memory Allocated: 4GB

**Comment by wraithkrown** [comment]
I have same issue in single player.  I am playing on stone block map if that is helpful.

**Comment by VallenFrostweaver** [comment]
This is a heavier pack. I suspect that the memory spikes or tries to and it crashes at that point as it doesn't have enough RAM. I suggest upping to 6GB (assuming you have at least 4 to allocate to PC) and try again.  I have nothing to found this on but that I have experienced similar in the past.

**Comment by wraithkrown** [comment]
For mod packs I keep it maxed (I have 32 gig of ram mostly for modded MC).  On the bright side, at least last time it crashed, it reloaded me in the nether.  The 10-20 times before that it would reload me in the overworld.  Also this time I started a new world so maybe the old world was corrupted somehow?  I even tried deleting dim -1 on the old world but that did not help.  I have seen very few complaints via Google so it might just be a rare occurrence.

**Comment by DocConnors** [comment]
I'm having the same issue. My dedicated server has 10GB just for it and performs exactly the same. About a minute of lag followed by a server crash "ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)"

**Comment by scollenburg** [comment]
Hi @asdfwasfdad - 

I'm helping develop of Telepastries. Can you provide the last 1 minute or so of the debug log before the crash?

**Comment by scollenburg** [comment]
@wraithkrown and @DocConnors , are you still having issues with current versions of the pack? If so, please upload a copy of the last minute or so of the debug log (eg to pastebin) & give a link along with the pack version you are using at the time. Thanks!

**Comment by asdfwasfdad** [comment]
Thank you for the email and I'm sorry for such a late response.
I jumped from Sky Factory 4 version 4.0.1 to version 4.0.5, so I'm not too
sure at which version the problem was fixed for me, but as of update 4.0.5
I haven't seen any noticeable problems yet, but if I find any problems I'll
be glad to discuss it with you in the future if you are available.

Thank you very much.

**Comment by ChillinChicken** [comment]
I would like to through my hat into the ring of folks having this problem, using the current version of the pack (4.0.8).
Server has 6GB dedicated, currently running Windows 10.

Here are the crash logs:
https://pastebin.com/dLFYmRJB
https://pastebin.com/LNZNy7hB
https://pastebin.com/dU8Vwqvh

**Comment by AlexejheroYTB** [comment]
I am having the same issue. Server crashes with 
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
```

**Comment by scollenburg** [comment]
@ChillinChicken - Sorry it took me so long to get back to you, I must have missed the original notification. The error logs show an issues with tinkers Construct:

```
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
    at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:89)
    at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:280)
    at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:266)
```

Please report the issue on their tracker: https://github.com/SlimeKnights/TinkersConstruct/issues
