### ISSUE TITLE
Vanilla leaves are not making sugar cane seeds when placed into crushing tub, only modded ones will.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#48]
Vanilla leaves are not making sugar cane seeds when placed into crushing tub, only modded ones will.

**Comment by justinrusso** [comment]
This seems to be any of them that have subitems. Any individual ones that were in the oredict work.

Should be a way to improve the loop to get each individual item instead of `:*` as added in the oredict... or just remove the `:*` from oredict and add manually like it was done in SevTech for wood logs.

**Comment by darkphan** [comment]
This is broke again.

**Comment by justinrusso** [comment]
Check your crafttweaker log. Are there any errors?

**Comment by darkphan** [comment]
This might help:

`[INITIALIZATION][SERVER][INFO] [crafttweaker | SIDE_SERVER]: Loading Script: {[2600:crafttweaker]: crafttweaker/oredict/leaves.zs}
[INITIALIZATION][SERVER][INFO] Removing Jungle Leaves from ore dictionary entry treeLeaves
[INITIALIZATION][SERVER][ERROR] [crafttweaker]: Error executing {[2600:crafttweaker]: crafttweaker/oredict/leaves.zs}: Index: 9, Size: 0
java.lang.IndexOutOfBoundsException: Index: 9, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at crafttweaker.mc1120.actions.ActionOreDictRemoveItem.apply(ActionOreDictRemoveItem.java:21)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:57)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
	at crafttweaker.mc1120.oredict.MCOreDictEntry.remove(MCOreDictEntry.java:146)
	at crafttweaker\oredict\Leaves.__script__(crafttweaker/oredict/leaves.zs:18)
	at __ZenMain__.run(crafttweaker\oredict\Leaves)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:221)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_478_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:814)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:624)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by justinrusso** [comment]
Yeah, I have reported this to CraftTweaker. Didn't realize this was affecting the master build as well.

**Comment by Darkosto** [comment]
Just checked this out and it looks fixed. There are a few leaves that do not work such as Totemic, but the majority of them including vanilla works.
