### ISSUE TITLE
World not loading stuck on loading terrain

### ISSUE THREAD

**Issue by zQwex** [Darkosto/SkyFactory4Issues#547]
## Bug Report
As soon as I enter an offline world, the screen remains at the loading screen. I have reinstalled the modpack even that does not help.

## Expected Behaviour
I would actually join the world instead I stay in the loading screen

## Possible Solution
I have no idea why that is

## Steps to Reproduce (for bugs)
1. http://prntscr.com/nf2m65

## Logs
* Client/Server Log:
The log was too long and I could not find a site where you could upload texts for so long so I had to upload the file to Mediafire : 

http://www.mediafire.com/file/5w23s11naw8w41d/latest.log/file

* Crash Log: Game does not crash

## World Information
* Preset: Skyfactory 4

* Prestige: no

* Modpack Version world created in: 4.0.1

* Additional Content Installed: /

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_202
* Launcher Used: Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

##Sorry for my bad english i am german

**Comment by zQwex** [comment]
I tried it over because AT-Launcher and there comes the following error code:

[22/4/2019 17:20:59 PM] Exception in thread "Server thread" [17:20:59] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[22/4/2019 17:20:59 PM] [17:20:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Thread.run(Unknown Source)
[22/4/2019 17:22:18 PM] [17:22:18] [Client thread/ERROR] [minecraft/SaveFormatOld]: Exception reading **USERSDIR**\Instances\SkyFactory4\saves\SkyFactory 4\level.dat
[22/4/2019 17:22:18 PM] java.lang.NullPointerException: null

**Comment by pepe-vic** [comment]
Hi ! did you actually find any solution to your problem because i have exactly the same right now ^^
