### ISSUE TITLE
Server has many errors and I time out when joining the server

### ISSUE THREAD

**Issue by MayusYT** [Darkosto/SkyFactory4Issues#658]
## Bug Report
Server log is spammed with many, many errors and I time out when trying to join the server.

* Client/Server Log: https://pastebin.pl/view/1d541f34

## World Information

* Preset: SF4 Classic

* Prestige: No

* Modpack Version world created in: 4.0.2

## Server Information
* Java Version: 8
* Operating System: Linux Mint
* Hoster/Hosting Solution: Self-Hosted
* Sponge (Non-Vanilla Forge) Server: /

**Comment by MayusYT** [comment]
Here's a picture of the error: https://i.imgur.com/sGeaQdx.png

**Comment by MayusYT** [comment]
Client log: 
```
[17:54:14] [Session-Validator/INFO]: Session validation successful
[17:54:17] [Client thread/INFO]: Connecting to snapecraft.net, 3587
[17:54:38] [Server Connector #7/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: snapecraft.net/88.130.76.156:3587
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_51]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_51]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51]
Caused by: java.net.ConnectException: Connection timed out: no further information
	... 10 more
```

**Comment by MayusYT** [comment]
Turned out that the port wasn't forwareded. Silly me :D
