### ISSUE TITLE
Simple Storage Network Remote Control GUI not opening

### ISSUE THREAD

**Issue by ratkinsonuk** [Darkosto/SkyFactory4Issues#786]
Playing version 4.0.2 of the SF4 pack, crafted the SSN remote control and the GUI wouldn't open despite setting the network on the controller.

Checked the log files, and I can see this :-  

[00:21:21] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Sending packet
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: net.minecraft.util.ReportedException: Sending packet
	at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:895) ~[pa.class:?]
	at mrriegel.storagenetwork.util.UtilTileEntity.updateTile(UtilTileEntity.java:111) ~[UtilTileEntity.class:?]
	at mrriegel.storagenetwork.gui.GuiHandler.getServerGuiElement(GuiHandler.java:52) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at mrriegel.storagenetwork.item.remote.ItemRemote.func_77659_a(ItemRemote.java:123) ~[ItemRemote.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.network.EnumConnectionState.func_150752_a(SourceFile:349) ~[gx.class:?]
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:209) ~[gw.class:?]
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:168) ~[gw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:882) ~[pa.class:?]
	at mrriegel.storagenetwork.util.UtilTileEntity.updateTile(UtilTileEntity.java:111) ~[UtilTileEntity.class:?]
	at mrriegel.storagenetwork.gui.GuiHandler.getServerGuiElement(GuiHandler.java:52) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at mrriegel.storagenetwork.item.remote.ItemRemote.func_77659_a(ItemRemote.java:123) ~[ItemRemote.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[00:21:23] [Server thread/INFO]: Saving and pausing game...

I've upgraded to v4.0.3, but still getting the same issue.

I'm playing on the standard world preset with Prestige enabled.

[latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/3133474/latest.log)

**Comment by Chunkimunki** [comment]
same :(
