### ISSUE TITLE
Crash when putting acorns in advanced crusher

### ISSUE THREAD

**Issue by Moogri** [Darkosto/SkyFactory4Issues#819]
As the topic suggests when i put iron acorns in the Advanced Crushing Machine my client CTD's.  This is Sky Factory 4.0.3

Error log points to the following code; 
[Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at mekanism.common.inventory.container.ContainerFactory$FactoryInputSlot.func_75214_a(ContainerFactory.java:203) ~[ContainerFactory$FactoryInputSlot.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146273_a(GuiContainer.java:469) ~[bmg.class:?]
	at mekanism.client.gui.GuiMekanism.func_146273_a(GuiMekanism.java:125) ~[GuiMekanism.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) ~[blk.class:?]
	at mekanism.client.gui.GuiMekanism.func_146274_d(GuiMekanism.java:141) ~[GuiMekanism.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) ~[bib.class:?]

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
