### ISSUE TITLE
Game crashes when equipping Ion Sniper from Matter Overdrive

### ISSUE THREAD

**Issue by General353** [Darkosto/SkyFactory4Issues#833]
## Bug Report
Game stops responding when equipping Ion Sniper from Matter Overdrive, and needs to be force closed
Had no issues with using the weapon when on version 4.0.3, but after updating to 4.0.5 i cannot equip the weapon without the game crashing. 3 out of the last 4 times that i have scrolled past the weapon on the hotbar, the game crashed.

## Steps to Reproduce (for bugs)
1. Have Matter Overdrive Ion Sniper on hotbar
2. Take out Ion Sniper 
3. Game stops responding and needs force closed

Weapon has been upgraded with the sniper scope, Dilithium Focusing Matrix, and a max size battery

## Logs
* Client/Server Log: pastebin.com/VMM8Y2XL
* Crash Log: Had to force close minecraft, no crash report was generated

## World Information
Preset: Sky Factory 4
Prestige: No
Modpack Version world created in: 4.0.1
Additional Content Installed: None

## Client Information
Modpack Version: 4.0.5
Java Version: 1.8.0.211
Launcher Used: Twitch
Memory Allocated: 8 gb
Server/LAN/Single Player: Single
Optifine Installed: No
Shaders Enabled: No

**Comment by IanKemp** [comment]
Have experienced the exact same bug, except with the latest SF4 (4.1.0). I have no crash log because of the hard freeze, and I'm running the game via the Twitch client with no extra mods loaded.

It's important to note that this only seems to happen after Minecraft has been running for a while (a few hours). It may also be related to the fact that the rifle I'm using (Phaser Rifle in my case) also has a scope like OP's.

The last exception before the JVM hard-locks is identical to the one posted by OP:

```
[21:00:08] [Netty Server IO #3/ERROR]: There was a critical exception handling a packet on channel mo_channel
java.lang.RuntimeException: PLAYER target expects a Player arg
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:136) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:367) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at matteroverdrive.network.PacketPipeline.sendTo(PacketPipeline.java:143) ~[PacketPipeline.class:?]
	at matteroverdrive.entity.android_player.AndroidPlayer.sync(AndroidPlayer.java:458) ~[AndroidPlayer.class:?]
	at matteroverdrive.entity.android_player.AndroidPlayer.sync(AndroidPlayer.java:446) ~[AndroidPlayer.class:?]
	at matteroverdrive.entity.android_player.AndroidPlayer.receiveEnergy(AndroidPlayer.java:409) ~[AndroidPlayer.class:?]
	at matteroverdrive.tile.TileEntityMachineChargingStation.manageAndroidCharging(TileEntityMachineChargingStation.java:70) ~[TileEntityMachineChargingStation.class:?]
	at matteroverdrive.tile.TileEntityMachineChargingStation.func_73660_a(TileEntityMachineChargingStation.java:57) ~[TileEntityMachineChargingStation.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
