### ISSUE TITLE
SkyFactory 4 Won't load up the server, PLZ Help

### ISSUE THREAD

**Issue by Number1weakling** [Darkosto/SkyFactory4Issues#886]
## Bug Report
It launches up fine but when I open my world it just starts loading and it never stops.
It just started out of nowhere.
Crash Log:[08/5/2019 17:58:11 PM] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: **USERSDIR**\Instances\SkyFactory4\crash-reports\crash-2019-05-08_17.58.11-server.txt
[08/5/2019 17:58:11 PM] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[08/5/2019 17:58:11 PM] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[08/5/2019 17:58:11 PM] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[08/5/2019 17:58:13 PM] [Server thread/INFO] [foamfix]: JEI search tree manager injection complete!
[08/5/2019 17:58:14 PM] [Server thread/INFO] [FML]: Applying holder lookups
[08/5/2019 17:58:14 PM] [Server thread/INFO] [FML]: Holder lookups applied
[08/5/2019 17:58:14 PM] [Server thread/INFO] [fluxnetworks]: Cleared Network Caches
[08/5/2019 17:58:14 PM] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 0 data blobs
[08/5/2019 17:58:14 PM] [Server thread/WARN] [opencomputers]: Error handling file saving: Did the server never start?
[08/5/2019 17:58:14 PM] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[08/5/2019 17:58:14 PM] Exception in thread "Server thread" [17:58:14] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[08/5/2019 17:58:14 PM] [17:58:14] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Thread.run(Unknown Source)
[08/5/2019 17:59:21 PM] Killing Minecraft
[08/5/2019 17:59:21 PM] Checking for updated files!
[08/5/2019 17:59:23 PM] No updates found!
[08/5/2019 17:59:24 PM] Log uploaded and link copied to clipboard: https://paste.atlauncher.com/view/0a17a893

**Comment by shortybsd** [comment]
Looks like your world save is corrupted from a power outage or your pc crashing and shutting down. Server will not start due to NBT tags all being butchered. A simple fix, is to fix the corrupted chunks with mcedit or pull from a backup. Since this pack doesn't run FTB Utilites, grab aroma's backup.

**Comment by justinrusso** [comment]
Check out the discord for help http://bit.ly/DarkostoDiscord
